// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4mIMsyI1q9dF59OAt8M9n0dmUn32pBfo',
    appId: '1:467383920618:web:5837d585ef3bd32516b493',
    messagingSenderId: '467383920618',
    projectId: 'project1-b0a9e',
    authDomain: 'project1-b0a9e.firebaseapp.com',
    storageBucket: 'project1-b0a9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxBZp1Pt477lGnCLofg_kgg_wiLdswhA',
    appId: '1:467383920618:android:47aa1a8976465d8616b493',
    messagingSenderId: '467383920618',
    projectId: 'project1-b0a9e',
    storageBucket: 'project1-b0a9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1467-iQSaVdvO3RoEkx033BJNfjEwJ8',
    appId: '1:467383920618:ios:e594eb603b1255e416b493',
    messagingSenderId: '467383920618',
    projectId: 'project1-b0a9e',
    storageBucket: 'project1-b0a9e.appspot.com',
    iosClientId: '467383920618-hcdqrbs5o795448rbq5shfb2u1g787c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1467-iQSaVdvO3RoEkx033BJNfjEwJ8',
    appId: '1:467383920618:ios:e594eb603b1255e416b493',
    messagingSenderId: '467383920618',
    projectId: 'project1-b0a9e',
    storageBucket: 'project1-b0a9e.appspot.com',
    iosClientId: '467383920618-hcdqrbs5o795448rbq5shfb2u1g787c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
